/* Generates docs/TEST_REPORT.md from the executed tests/results.json. */
'use strict';
const fs = require('fs');
const path = require('path');
const r = JSON.parse(fs.readFileSync(path.join(__dirname, 'results.json'), 'utf8'));
const today = new Date().toISOString().slice(0, 10);

const areaRows = Object.keys(r.byArea).sort().map(a => {
  const g = r.byArea[a];
  return `| ${a} | ${g.t} | ${g.p} | ${g.f} |`;
}).join('\n');

const groups = {};
r.results.forEach(t => { (groups[t.area] = groups[t.area] || []).push(t); });
const detail = Object.keys(groups).sort().map(area => {
  const rows = groups[area].map(t =>
    `| ${t.id} | ${t.desc} | ${t.status === 'PASS' ? '✅ PASS' : '❌ FAIL — ' + t.detail} |`).join('\n');
  return `#### ${area}\n\n| ID | Test | Result |\n|----|------|--------|\n${rows}\n`;
}).join('\n');

const md = `# Deutsch Wortschatz — Software Test Report

**German vocabulary learning app · Levels A1 · A2 · B1 · themed phrasebook**
**Result: ${r.passed} of ${r.total} automated tests passed (${r.failed} failed).**
Test run date: ${today} · Generated by \`npm test\` (\`tests/run.js\`).

---

## 1. Scope

This report records automated testing of the Deutsch Wortschatz application — a German vocabulary learning app delivered as a Capacitor web app that ships to **web, Android, and iOS from a single codebase** (\`www/index.html\`). It covers the three content levels (A1, A2, B1), the themed phrasebook, the spaced-repetition engine, onboarding and profiles (including the vocabulary filter and PIN lock), data persistence and backup, the daily story feature, and build/config integrity.

The suite is **executable**: it loads the application's *real* JavaScript and data into a mocked-browser sandbox (Node.js) and asserts actual behaviour. Every result below was produced by running the code — not by inspection.

## 2. Method

\`tests/run.js\` extracts the inline \`<script>\` from \`www/index.html\`, evaluates it inside a Node \`vm\` sandbox with lightweight mocks for the browser environment (\`document\`, \`localStorage\`, \`speechSynthesis\`, timers, Capacitor), then exercises the exposed data and pure logic — word lists, the SRS engine, the vocabulary filter, sessions, the data store, profiles, custom words, and the story rotation. Date-dependent behaviour is driven through the app's own \`simOffset\` test hook. Each test has an ID, an area, a description, and a live PASS/FAIL result.

**Run it yourself:**
\`\`\`bash
npm test          # runs the suite, prints the table, exits non-zero on any failure
npm run test:report   # runs the suite and regenerates this document
\`\`\`

## 3. Results at a glance

| Test area | Tests | Passed | Failed |
|-----------|-------|--------|--------|
${areaRows}
| **TOTAL** | **${r.total}** | **${r.passed}** | **${r.failed}** |

${r.failed === 0 ? 'All automated checks passed. No defects were found in the tested logic during this run.' : '⚠️ Some checks failed — see the detail table below.'}

## 4. Detailed results (Part A — automated)

${detail}

---

## 5. Part B — Manual UI test plan

These cases require a real device (or simulator) because they exercise audio, touch, rendering and native plugins that the automated harness mocks. Run them on iOS and Android after each release.

| ID | Area | Steps | Expected result |
|----|------|-------|-----------------|
| M-01 | Launch | Cold-launch the app | Splash shows, then the login/welcome card appears |
| M-02 | Onboarding | Enter a name, tap **Get started**, choose a level & words/day | Home screen appears for the chosen level |
| M-03 | PIN | Set a PIN, relaunch | App asks for the PIN before unlocking; wrong PIN is rejected |
| M-04 | Audio (TTS) | Tap the 🔊 on a flashcard | The German word is spoken by the device voice |
| M-05 | Study | Add words, flip a card, rate **Got it / Again** | Card advances; progress and streak update |
| M-06 | Review | Advance the test-date bar, open **Review** | Due cards appear and can be rated |
| M-07 | Stories | Open **Stories**, play audio, take the quiz | Sentences read aloud; quiz scores correctly |
| M-08 | Games | Open **Games**, play the picture/emoji quiz | Answers register; score shown |
| M-09 | Themes | Open **Themen-Wortschatz**, pick a topic | Topic word list renders and is studyable |
| M-10 | My Words | Add a custom word, study it | Custom word appears in study/review/games |
| M-11 | Backup | Settings → **Export**, then **Import** the file | Progress is exported and restored via the share sheet |
| M-12 | Levels | Switch level in Settings | Progress, reviews and history are independent per level |
| M-13 | Offline | Enable airplane mode, use the app | Everything works with no network |
| M-14 | Persistence | Force-quit and relaunch | Profile, progress and settings are retained |

## 6. Notes & known limitations

- The automated suite covers logic and data; it mocks the browser, so on-device audio, touch and rendering are validated manually (Part B).
- B2 and C1 levels are wired into the UI but marked "coming soon" until their word lists are added; tests assert those levels report as empty rather than erroring.
- The yellow **"Test date"** simulator bar is a QA aid and should be removed before a public App Store release.

---

*Generated from \`tests/results.json\` — re-run \`npm run test:report\` to refresh.*
`;

fs.writeFileSync(path.join(__dirname, '..', 'docs', 'TEST_REPORT.md'), md, 'utf8');
console.log('Wrote docs/TEST_REPORT.md (' + r.passed + '/' + r.total + ' passed)');
